### ISSUE TITLE
`getgrnam': can't find group for rvm (ArgumentError)

### ISSUE THREAD

**Issue by TrevorBramble** [martinisoft/chef-rvm#110]
Halp?

EDIT:
This is on Scientific Linux 6.1 inside of Vagrant, for what it's worth!

```
[Tue, 19 Jun 2012 17:19:25 -0400] INFO: execute[Add bundler to /usr/local/rvm/gemsets/global.gems] sh(echo "bundler" >> "/usr/local/rvm/gemsets/global.gems")
[Tue, 19 Jun 2012 17:19:26 -0400] ERROR: execute[Add bundler to /usr/local/rvm/gemsets/global.gems] (/srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb line 79) has had an error
[Tue, 19 Jun 2012 17:19:26 -0400] ERROR: rvm_global_gem[bundler] (rvm::user line 183) has had an error
[Tue, 19 Jun 2012 17:19:26 -0400] ERROR: rvm_global_gem[bundler] (/srv/chef/file_store/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:183:in `install_rubies') had an error:
rvm_global_gem[bundler] (rvm::user line 183) had an error: Chef::Exceptions::ShellCommandFailed: execute[Add bundler to /usr/local/rvm/gemsets/global.gems] (/srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb line 79) had an error: Chef::Exceptions::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of echo "bundler" >> "/usr/local/rvm/gemsets/global.gems" ----
STDOUT: 
STDERR: /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:139:in `getgrnam': can't find group for rvm (ArgumentError)
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:139:in `gid'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:79:in `set_group'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:188:in `fork_subprocess'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:185:in `fork'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:185:in `fork_subprocess'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:17:in `run_command'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:180:in `run_command'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/mixin/shell_out.rb:30:in `shell_out'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/mixin/shell_out.rb:35:in `shell_out!'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider/execute.rb:58:in `action_run'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `send'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `run_action'
	from /srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb:94:in `update_global_gems_file'
	from /srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb:31:in `class_from_file'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider.rb:104:in `instance_eval'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider.rb:104:in `action_install'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `send'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `run_action'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:45:in `run_action'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `each'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:76:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:312:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:160:in `run'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:239:in `run_application'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in `loop'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in `run_application'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application.rb:67:in `run'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/chef-client:26
	from /usr/bin/chef-client:19:in `load'
	from /usr/bin/chef-client:19
---- End output of echo "bundler" >> "/usr/local/rvm/gemsets/global.gems" ----
Ran echo "bundler" >> "/usr/local/rvm/gemsets/global.gems" returned 1
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:206:in `invalid!'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:192:in `error!'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider/execute.rb:58:in `action_run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `send'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `run_action'
/srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb:94:in `update_global_gems_file'
/srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb:31:in `class_from_file'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider.rb:104:in `instance_eval'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider.rb:104:in `action_install'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `send'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:45:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:76:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:312:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:160:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:239:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in `loop'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application.rb:67:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/chef-client:26
/usr/bin/chef-client:19:in `load'
/usr/bin/chef-client:19
[Tue, 19 Jun 2012 17:19:26 -0400] ERROR: Running exception handlers
[Tue, 19 Jun 2012 17:19:26 -0400] FATAL: Saving node information to /srv/chef/file_store/failed-run-data.json
[Tue, 19 Jun 2012 17:19:26 -0400] ERROR: Exception handlers complete
[Tue, 19 Jun 2012 17:19:26 -0400] FATAL: Stacktrace dumped to /srv/chef/file_store/chef-stacktrace.out
[Tue, 19 Jun 2012 17:19:26 -0400] FATAL: Chef::Exceptions::ShellCommandFailed: rvm_global_gem[bundler] (rvm::user line 183) had an error: Chef::Exceptions::ShellCommandFailed: execute[Add bundler to /usr/local/rvm/gemsets/global.gems] (/srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb line 79) had an error: Chef::Exceptions::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of echo "bundler" >> "/usr/local/rvm/gemsets/global.gems" ----
STDOUT: 
STDERR: /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:139:in `getgrnam': can't find group for rvm (ArgumentError)
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:139:in `gid'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:79:in `set_group'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:188:in `fork_subprocess'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:185:in `fork'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:185:in `fork_subprocess'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out/unix.rb:17:in `run_command'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/shell_out.rb:180:in `run_command'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/mixin/shell_out.rb:30:in `shell_out'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/mixin/shell_out.rb:35:in `shell_out!'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider/execute.rb:58:in `action_run'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `send'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `run_action'
	from /srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb:94:in `update_global_gems_file'
	from /srv/chef/file_store/cookbooks/rvm/providers/global_gem.rb:31:in `class_from_file'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider.rb:104:in `instance_eval'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/provider.rb:104:in `action_install'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `send'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource.rb:440:in `run_action'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:45:in `run_action'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `each'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:81:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/runner.rb:76:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:312:in `converge'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:160:in `run'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:239:in `run_application'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in `loop'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in `run_application'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application.rb:67:in `run'
	from /usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/chef-client:26
	from /usr/bin/chef-client:19:in `load'
	from /usr/bin/chef-client:19
---- End output of echo "bundler" >> "/usr/local/rvm/gemsets/global.gems" ----
Ran echo "bundler" >> "/usr/local/rvm/gemsets/global.gems" returned 1
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chef-client -c /tmp/vagrant-chef-1/client.rb -j /tmp/vagrant-chef-1/dna.json
```

From the role file:
```
run_list ...
         "recipe[rvm::user]",
         "recipe[rvm::vagrant]",

...

default_attributes "rvm"      => {"default_ruby"  => "ree-1.8.7-2011.03",
                                  "global_gems"   => [{"name" => "chef"},
                                                      {"name" => "rake"},
                                                      {"name" => "bundler"}],
                                  "install_pkgs"  => ['readline'],
                                  "user_installs" => ['vagrant']
                                  },
...
```

**Comment by cmluciano** [comment]
@TrevorBramble Did you find a workaround for this?

**Comment by TrevorBramble** [comment]
@cmluciano I don't recall, but this platform is long behind me so I'm going to go ahead and close the issue.

**Comment by bleriaud** [comment]
getting the same error on rhel74 vagrant. Any workaround here?
