### ISSUE TITLE
JRuby installation crashes

### ISSUE THREAD

**Issue by meskyanichi** [martinisoft/chef-rvm#113]
Hi. It seemed that it did in fact install, but when re-running the Chef recipe it will error out with the following:

```
[Mon, 02 Jul 2012 17:11:47 +0200] INFO: Processing template[/home/deployer/.rvmrc] action create (rvm::user_install line 140)
[Mon, 02 Jul 2012 17:11:47 +0200] INFO: Processing execute[install user RVM for deployer] action run (rvm::user_install line 76)
[Mon, 02 Jul 2012 17:11:47 +0200] INFO: Processing execute[upgrade user RVM for deployer to none] action run (rvm::user_install line 110)
[Mon, 02 Jul 2012 17:11:47 +0200] INFO: Processing rvm_ruby[jruby-1.6.7.2] action install (rvm::user line 170)
[Mon, 02 Jul 2012 17:11:49 +0200] ERROR: rvm_ruby[jruby-1.6.7.2] (rvm::user line 170) has had an error
[Mon, 02 Jul 2012 17:11:49 +0200] ERROR: rvm_ruby[jruby-1.6.7.2] (/tmp/chef-solo/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:170:in `block in install_rubies') had an error:
rvm_ruby[jruby-1.6.7.2] (rvm::user line 170) had an error: ArgumentError: syntax error on line 38, col 3: `'
/opt/chef/embedded/lib/ruby/1.9.1/syck.rb:135:in `load'
/opt/chef/embedded/lib/ruby/1.9.1/syck.rb:135:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rvm-1.11.3.4/lib/rvm/shell/abstract_wrapper.rb:139:in `raw_stdout_to_parts'
/tmp/chef-solo/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:51:in `block in run_command'
/tmp/chef-solo/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:78:in `with_shell_instance'
/tmp/chef-solo/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:45:in `run_command'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rvm-1.11.3.4/lib/rvm/shell/abstract_wrapper.rb:71:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rvm-1.11.3.4/lib/rvm/environment/utility.rb:71:in `rvm'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rvm-1.11.3.4/lib/rvm/environment/list.rb:17:in `list_strings'
/tmp/chef-solo/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:41:in `update_installed_rubies'
/tmp/chef-solo/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:33:in `installed_rubies'
/tmp/chef-solo/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:51:in `ruby_installed?'
/tmp/chef-solo/cookbooks/rvm/providers/ruby.rb:34:in `block in class_from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/provider.rb:106:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/provider.rb:106:in `block in action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource.rb:454:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/runner.rb:85:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/runner.rb:85:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/runner.rb:85:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource_collection.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/client.rb:330:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/client.rb:163:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/application/solo.rb:207:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/application/solo.rb:195:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/application/solo.rb:195:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/lib/chef/application.rb:70:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.12.0/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:19:in `load'
/usr/bin/chef-solo:19:in `<main>'
[Mon, 02 Jul 2012 17:11:49 +0200] ERROR: Running exception handlers
[Mon, 02 Jul 2012 17:11:49 +0200] ERROR: Exception handlers complete
[Mon, 02 Jul 2012 17:11:49 +0200] FATAL: Stacktrace dumped to /tmp/chef-solo/chef-stacktrace.out
[Mon, 02 Jul 2012 17:11:49 +0200] FATAL: ArgumentError: rvm_ruby[jruby-1.6.7.2] (rvm::user line 170) had an error: ArgumentError: syntax error on line 38, col 3: `'
```

My node config looks like this:

```json

  "rvm": {
    "user_installs": [
      {
        "user": "deployer",
        "default_ruby": "jruby-1.6.7.2",
        "rubies": ["jruby-1.6.7.2"], // ["ruby-1.9.3", "jruby-1.6.7.2"],
        "gems": {
          // "ruby-1.9.3": [
          //   { "name": "bundler" }
          // ],
          "jruby-1.6.7.2": [
            // { "name": "bundler" },
            // { "name": "jruby-openssl" }
          ]
        }
      }
    ]
  }
```

Tried various combinations, adding/removing (as you can see by the comments) but it keeps crashing only on JRuby. Any idea why?

**Comment by cmluciano** [comment]
The error in the original log file appears to be a syntax error in user_install. Closing this for now. @dpisarewski can you please open up a different issue with your information?
