### ISSUE TITLE
Method-scoped rvm_wrap_cmd is failing

### ISSUE THREAD

**Issue by josephholsten** [martinisoft/chef-rvm#139]
This patch really isn't working for me: https://github.com/fnichol/chef-rvm/commit/b5313cb5e1ff0784b128e42ca0f0fd164c4ca1e0 (even with this https://github.com/fnichol/chef-rvm/commit/d6cdb2ab93c421ca6234cbaf5548c914eba4084f)

Reverting `libraries/chef_rvm_recipe_helpers.rb` to the [version in v0.9.0](https://github.com/fnichol/chef-rvm/blob/v0.9.0/libraries/chef_rvm_recipe_helpers.rb)  fixed it.

Chef version: 10.16.0 Omnibus
Platform: Ubuntu 12.04

Log output:

    [2012-11-15T13:45:02-08:00] INFO: Processing chef_gem[rvm] action install (rvm::default line 21)
    /var/cache/chef/cookbooks/rvm/libraries/rvm_chef_user_environment.rb:51: warning: class variable access from toplevel

    ================================================================================
    Recipe Compile Error in /var/cache/chef/cookbooks/rvm/recipes/system.rb
    ================================================================================

    NameError
    ---------
    Cannot find a resource for rvm_wrap_cmd on ubuntu version 12.04

    Cookbook Trace:
    ---------------
      /var/cache/chef/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:77:in `install_rvm'
      /var/cache/chef/cookbooks/rvm/recipes/system_install.rb:49:in `from_file'
      /var/cache/chef/cookbooks/rvm/recipes/system.rb:20:in `from_file'

    Relevant File Content:
    ----------------------
    /var/cache/chef/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:

     70:          else
     71:            user_dir    = nil
     72:            exec_name   = "install system-wide RVM"
     73:            exec_env    = { 'TERM' => 'dumb' }
     74:          end
     75:  
     76:          rvm_installed_check = rvm_wrap_cmd(
     77>>             %{type rvm | cat | head -1 | grep -q '^rvm is a function$'}, user_dir
     78:          )
     79:  
     80:          i = execute exec_name do
     81:            user    opts[:user] || "root"
     82:            command "curl -L #{opts[:installer_url]} | bash #{opts[:script_flags]}"
     83:            environment(exec_env)
     84:  
     85:            # excute in compile phase if gem_package recipe is requested
     86:            if install_now

    [2012-11-15T13:45:03-08:00] ERROR: Running exception handlers
    [2012-11-15T13:45:15-08:00] FATAL: Saving node information to /var/cache/chef/failed-run-data.json
    [2012-11-15T13:45:20-08:00] ERROR: Exception handlers complete
    [2012-11-15T13:45:20-08:00] FATAL: Stacktrace dumped to /var/cache/chef/chef-stacktrace.out
    [2012-11-15T13:45:20-08:00] FATAL: NameError: Cannot find a resource for rvm_wrap_cmd on ubuntu version 12.04

**Comment by cmluciano** [comment]
Is this still an issue? @josephholsten @bscott

**Comment by cmluciano** [comment]
Closing due to inactivity, please reopen if this is still an issue
