### ISSUE TITLE
recipe['rvm::system'] >> no candidate version available for libffi-devel

### ISSUE THREAD

**Issue by tsai146** [martinisoft/chef-rvm#143]
Can anyone help me to resolve this issue?

My environment: 
Chef version 10.16.2.
Running on redhat 6.3
Cookbook v0.9.0

<pre>
[2012-11-30T00:46:10-08:00] INFO: Processing package[libffi-devel] action install (/var/chef/cache/cookbooks/rvm/providers/ruby.rb line 156)

================================================================================
Error executing action `install` on resource 'package[libffi-devel]'
================================================================================

Chef::Exceptions::Package
-------------------------
No version specified, and no candidate version available for libffi-devel

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:158:in `block in install_ruby_dependencies'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:155:in `each'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:155:in `install_ruby_dependencies'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:39:in `block in class_from_file'
/var/chef/cache/cookbooks/rvm/providers/environment.rb:74:in `ruby_resource'
/var/chef/cache/cookbooks/rvm/providers/environment.rb:39:in `block in class_from_file'
/var/chef/cache/cookbooks/rvm/providers/default_ruby.rb:41:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/rvm/providers/ruby.rb

156:     package pkg do
157:       action :nothing
158:     end.run_action(:install)
159:   end
160: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/rvm/providers/ruby.rb:156:in `block in install_ruby_dependencies'

package("libffi-devel") do
  action [:nothing]
  retries 0
  retry_delay 2
  package_name "libffi-devel"
  cookbook_name "rvm"
end

================================================================================
Error executing action `install` on resource 'rvm_ruby[ruby-1.9.3-p194]'
================================================================================

Chef::Exceptions::Package
-------------------------
package[libffi-devel] (/var/chef/cache/cookbooks/rvm/providers/ruby.rb line 156) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for libffi-devel

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:158:in `block in install_ruby_dependencies'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:155:in `each'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:155:in `install_ruby_dependencies'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:39:in `block in class_from_file'
/var/chef/cache/cookbooks/rvm/providers/environment.rb:74:in `ruby_resource'
/var/chef/cache/cookbooks/rvm/providers/environment.rb:39:in `block in class_from_file'
/var/chef/cache/cookbooks/rvm/providers/default_ruby.rb:41:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/rvm/providers/environment.rb

 70:     r = rvm_ruby @rubie do
 71:       user    new_resource.user
 72:       action :nothing
 73:     end
 74:     r.run_action(exec_action)

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/rvm/providers/environment.rb:70:in `ruby_resource'

rvm_ruby("ruby-1.9.3-p194") do
  action [:nothing]
  retries 0
  retry_delay 2
  cookbook_name "rvm"
  ruby_string "ruby-1.9.3-p194"
end

...
</pre>

**Comment by cmluciano** [comment]
This should be fixed in newer versions. Closing due to inactivity, please reopen if this is still an issue
