### ISSUE TITLE
rvm::system_install fails with Cannot find a resource for build_script_flags on ubuntu version 12.10

### ISSUE THREAD

**Issue by ghost** [martinisoft/chef-rvm#194]
<pre>
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/mycookbook/recipes/rvm-test.rb
================================================================================

NameError
---------
Cannot find a resource for build_script_flags on ubuntu version 12.10

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/rvm/recipes/system_install.rb:22:in `from_file'
  /var/chef/cache/cookbooks/mycookbook/recipes/rvm-test.rb:21:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/rvm/recipes/system_install.rb:

 15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 16:  # See the License for the specific language governing permissions and
 17:  # limitations under the License.
 18:  #
 19:  
 20:  include_recipe 'rvm'
 21:  
 22>> script_flags      = build_script_flags(node['rvm']['branch'], node['rvm']['version'])
 23:  upgrade_strategy  = build_upgrade_strategy(node['rvm']['upgrade'])
 24:  installer_url     = node['rvm']['installer_url']
 25:  rvm_prefix        = ::File.dirname(node['rvm']['root_path'])
 26:  rvm_gem_options   = node['rvm']['rvm_gem_options']
 27:  rvmrc             = node['rvm']['rvmrc']
 28:  
 29:  install_pkg_prereqs
 30:  
 31:  # Build the rvm group ahead of time, if it is set. This allows avoiding
</pre>

On a freshly installed Ubuntu 12.10

**Comment by cmluciano** [comment]
Is this still an issue for you? Do you have ```depends "rvm"``` in your metadata file?

**Comment by cmluciano** [comment]
Closing due to inactivity, please reopen if this is still an issue
