### ISSUE TITLE
Error executing action `install` on resource 'rvm_ruby[1.9.3]'

### ISSUE THREAD

**Issue by tsai146** [martinisoft/chef-rvm#218]
was follow the code provided here 
https://gist.github.com/bryanwb/4672266

and this is the error I am getting. 

```
================================================================================
Error executing action `install` on resource 'rvm_ruby[1.9.3]'
================================================================================

RVM::IncompleteCommandError
---------------------------
RVM::IncompleteCommandError

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:45:in `block in run_command'
/var/chef/cache/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:72:in `with_shell_instance'
/var/chef/cache/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:39:in `run_command'
/var/chef/cache/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:41:in `update_installed_rubies'
/var/chef/cache/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:33:in `installed_rubies'
/var/chef/cache/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:51:in `ruby_installed?'
/var/chef/cache/cookbooks/rvm/providers/ruby.rb:38:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb

176:           rvm_ruby ruby do
177:             patch            ruby_patch
178:             user             opts[:user]
179:             rubygems_version ruby_rubygems_version
180:           end
181:         end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:176:in `block in install_rubies'

rvm_ruby("1.9.3") do
  action :install
  retries 0
  retry_delay 2
  cookbook_name "rvm"
  recipe_name "user"
  user "app"
  ruby_string "1.9.3"
end

[2013-07-18T17:38:48-07:00] ERROR: Running exception handlers
[2013-07-18T17:38:49-07:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2013-07-18T17:38:49-07:00] ERROR: Exception handlers complete
[2013-07-18T17:38:49-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-07-18T17:38:49-07:00] FATAL: RVM::IncompleteCommandError: rvm_ruby[1.9.3] (rvm::user line 176) had an error: RVM::IncompleteCommandError: RVM::IncompleteCommandError
```

**Comment by cmluciano** [comment]
Closing due to inactivity, please reopen if this is still an issue
