### ISSUE TITLE
recipe compile error - can't convert symbol into integer

### ISSUE THREAD

**Issue by hbarrington** [martinisoft/chef-rvm#225]
here's a dump/stacktrace. Am I missing something obvious? Still new to chef.
I'll fork and play around with the code, if I find a fix do you accept pull requests?

```198.199.82.118 Compiling Cookbooks...
198.199.82.118 
198.199.82.118 Recipe: rvm::default
198.199.82.118 
198.199.82.118   * chef_gem[rvm] action install
198.199.82.118 
198.199.82.118 
198.199.82.118     - install version >= 1.11.3.6 of package rvm
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 /var/chef/cache/cookbooks/rvm/libraries/rvm_chef_user_environment.rb:49: warning: class variable access from toplevel
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 ================================================================================
198.199.82.118 
198.199.82.118 Recipe Compile Error in /var/chef/cache/cookbooks/rvm/recipes/system.rb
198.199.82.118 
198.199.82.118 ================================================================================
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 TypeError
198.199.82.118 
198.199.82.118 ---------
198.199.82.118 
198.199.82.118 can't convert Symbol into Integer
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 Cookbook Trace:
198.199.82.118 
198.199.82.118 ---------------
198.199.82.118 
198.199.82.118   /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:190:in `[]'
198.199.82.118 
198.199.82.118   /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:190:in `block in install_rubies'
198.199.82.118 
198.199.82.118   /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:189:in `each'
198.199.82.118 
198.199.82.118   /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:189:in `install_rubies'
198.199.82.118 
198.199.82.118   /var/chef/cache/cookbooks/rvm/recipes/system.rb:29:in `from_file'
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 
198.199.82.118 Relevant File Content:
198.199.82.118 
198.199.82.118 ----------------------
198.199.82.118 
198.199.82.118 /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:
198.199.82.118 
198.199.82.118 
198.199.82.118 183:          # set a default ruby
198.199.82.118 
198.199.82.118 184:          rvm_default_ruby opts[:default_ruby] do
198.199.82.118 
198.199.82.118 185:            user  opts[:user]
198.199.82.118 
198.199.82.118 186:          end
198.199.82.118 
198.199.82.118 187:  
198.199.82.118 
198.199.82.118 188:          # install global gems
198.199.82.118 
198.199.82.118 189:          opts[:global_gems].each do |gem|
198.199.82.118 
198.199.82.118 190>>           rvm_global_gem gem[:name] do
198.199.82.118 
198.199.82.118 191:              user      opts[:user]
198.199.82.118 
198.199.82.118 192:              [:version, :action, :options, :source].each do |attr|
198.199.82.118 
198.199.82.118 193:                send(attr, gem[attr]) if gem[attr]
198.199.82.118 
198.199.82.118 194:              end
198.199.82.118 
198.199.82.118 195:            end
198.199.82.118 
198.199.82.118 196:          end
198.199.82.118 
198.199.82.118 197:  
198.199.82.118 
198.199.82.118 198:          # install additional gems
198.199.82.118 
198.199.82.118 199:          opts[:gems].each_pair do |rstring, gems|```

**Comment by cmluciano** [comment]
Closing due to inactivity, please reopen if this is still an issue
