### ISSUE TITLE
gem files installed with chef-rvm are not usable in capistrano

### ISSUE THREAD

**Issue by DonGiulio** [martinisoft/chef-rvm#238]
Hello, 

I'm installing RVM and ruby and bundler with this cookbook, on my vagrant box. When I then use capistrano to deploy my application I get into troubles when capistrano tries to run the `bundle install`. 

for some reason capistrano will execute the default bundler, and this seems related to sudo. 

RVM and ruby and bundles were installed with: 

    include_recipe "rvm::user"
    include_recipe "rvm::vagrant"

my deploy.rb reads: 

    default[:rvm][:user_installs] = [
      { user: "vagrant",
        default_ruby: "2.0.0-p353",
        global_gems: [ { name: "bundler" } ]
      }
    ]
    
and the capistrano task is as follows: 
    
      task :bundle do
        on roles :app do
          within current_path do
            execute :whoami
            execute :which, :bundle
            execute :bundle, "-v"
            execute :bundle, :install
          end
        end
      end
      
which gives the following output

     INFO [3a3b32bc] Running /usr/bin/env whoami on 127.0.0.1
    DEBUG [3a3b32bc] Command: cd /var/www/shop/current && /usr/bin/env whoami
     INFO [3a3b32bc] Finished in 0.015 seconds with exit status 0 (successful).
    DEBUG [3a3b32bc] 	vagrant
     INFO [3a3b32bc] Finished in 0.015 seconds with exit status 0 (successful).
     INFO [b0f8f29d] Running /usr/bin/env which bundle on 127.0.0.1
    DEBUG [b0f8f29d] Command: cd /var/www/shop/current && /usr/bin/env which bundle
     INFO [b0f8f29d] Finished in 0.012 seconds with exit status 0 (successful).
    DEBUG [b0f8f29d] 	/usr/bin/bundle
     INFO [b0f8f29d] Finished in 0.012 seconds with exit status 0 (successful).
     INFO [9982167e] Running /usr/bin/env bundle -v on 127.0.0.1
    DEBUG [9982167e] Command: cd /var/www/shop/current && /usr/bin/env bundle -v
    DEBUG [9982167e] 	/usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8:in `require'
    DEBUG [9982167e] 	: 
    DEBUG [9982167e] 	no such file to load -- rubygems
    DEBUG [9982167e] 	 (
    DEBUG [9982167e] 	LoadError
    DEBUG [9982167e] 	)
    DEBUG [9982167e] 		from /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8
    DEBUG [9982167e] 		from /usr/lib/ruby/vendor_ruby/bundler.rb:11:in `require'
    DEBUG [9982167e] 		from /usr/lib/ruby/vendor_ruby/bundler.rb:11
    DEBUG [9982167e] 		from /usr/bin/bundle:4:in `require'
    DEBUG [9982167e] 		from /usr/bin/bundle:4
    cap aborted!

when I ssh to the vagrant box I get: 

    vagrant@shop-berkshelf:/var/www/shop/current$ which bundle
    /home/vagrant/.rvm/gems/ruby-2.0.0-p353@global/bin/bundle
    vagrant@shop-berkshelf:/var/www/shop/current$ sudo which bundle
    /usr/bin/bundle
    vagrant@shop-berkshelf:/var/www/shop/current$ bundle -v
    Bundler version 1.3.5
    vagrant@shop-berkshelf:/var/www/shop/current$ sudo bundle -v
    /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8:in `require': no such file to load -- rubygems (LoadError)
    	from /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8
    	from /usr/lib/ruby/vendor_ruby/bundler.rb:11:in `require'
    	from /usr/lib/ruby/vendor_ruby/bundler.rb:11
    	from /usr/bin/bundle:4:in `require'
    	from /usr/bin/bundle:4

any clue?

**Comment by cmluciano** [comment]
Closing due to inactivity, please reopen if this is still an issue
