### ISSUE TITLE
When i use "Raspberry pi" with Raspbian i see next error.

### ISSUE THREAD

**Issue by voleoo** [martinisoft/chef-rvm#275]
```

Recipe: rvm::default
  * chef_gem[rvm] action install (up to date)
/home/leoo/chef-solo/cookbooks-2/rvm/libraries/rvm_chef_user_environment.rb:49: warning: class variable access from toplevel

  ================================================================================
  Recipe Compile Error in /home/leoo/chef-solo/cookbooks-2/rvm/recipes/user.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `each' for nil:NilClass

  Cookbook Trace:
  ---------------
    /home/leoo/chef-solo/cookbooks-2/rvm/libraries/chef_rvm_recipe_helpers.rb:44:in `install_pkg_prereqs'
    /home/leoo/chef-solo/cookbooks-2/rvm/recipes/user_install.rb:22:in `from_file'
    /home/leoo/chef-solo/cookbooks-2/rvm/recipes/user.rb:20:in `from_file'

  Relevant File Content:
  ----------------------
  /home/leoo/chef-solo/cookbooks-2/rvm/libraries/chef_rvm_recipe_helpers.rb:

   37:            strategy
   38:          end
   39:        end
   40:
   41:        def install_pkg_prereqs(install_now = node.recipe?("rvm::gem_package"))
   42:          return if mac_with_no_homebrew
   43:
   44>>         node['rvm']['install_pkgs'].each do |pkg|
   45:            p = package pkg do
   46:              # excute in compile phase if gem_package recipe is requested
   47:              if install_now
   48:                action :nothing
   49:              else
   50:                action :install
   51:              end
   52:            end
   53:            p.run_action(:install) if install_now


  Running handlers:
[2014-09-28T18:03:24+00:00] ERROR: Running exception handlers
  Running handlers complete
[2014-09-28T18:03:24+00:00] ERROR: Exception handlers complete
[2014-09-28T18:03:24+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  Chef Client failed. 1 resources updated in 65.04703669 seconds
[2014-09-28T18:03:25+00:00] ERROR: undefined method `each' for nil:NilClass
[2014-09-28T18:03:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.

```

```
  "rvm": {
    "branch": "stable",
    "user_installs": [{ 
      "user": "leoo",
      "default_ruby": "2.1.3@global",
      "rubies": ["2.1.3"]
    }]
  }
```

```
"recipe[rvm::user]"
```
This error only on Raspbian.
Please help me.

**Comment by cmluciano** [comment]
Closing due to inactivity, please reopen if this is still an issue

**Comment by JustinAiken** [comment]
Still an issue, seeing the exact same error in the same place...

**Comment by voleoo** [comment]
@JustinAiken which version of "chef-rvm" are you use?
I had this problem when i use old config with newest version of 'chef-rvm'

You can use specific versions of cookbook
For librarian in Cheffile
```
cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.2'
```

**Comment by JustinAiken** [comment]
This was with 0.9.2

Adding this to my node's attributes (like #180 does internally) does fix it:

```ruby
  "rvm": {
    "install_pkgs": ["sed", "grep", "tar", "gzip", "bzip2", "bash", "curl", "git-core"],
    ...
```
